name: automerge

on:
  pull_request:
    types:
      - labeled
      - reopened
      - unlocked
      - unlabeled
      - synchronize
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      -
        name: Automerge
        uses: pascalgn/automerge-action@v0.8.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ":bell: automerge,:game_die: dependencies"
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: automatic
          UPDATE_LABELS: ":bell: automerge,:game_die: dependencies"
