name: ci

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildx-version:
          - latest
          - v0.2.2
        qemu-version:
          - latest
          - 4.2.0-7
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: ./
        with:
          buildx-version: ${{ matrix.buildx-version }}
          qemu-version: ${{ matrix.qemu-version }}
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --output "type=image,push=false" \
            --file ./test/Dockerfile ./test
