name: uncommited

on:
  pull_request:
  push:

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      -
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v1
      -
        # https://github.com/actions/setup-node
        name: Set up Node
        uses: actions/setup-node@v1
      -
        name: Build
        run: |
          npm install
      -
        name: Pre-checkin
        run: |
          npm run pre-checkin
      -
        name: Check for uncommitted changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git status --porcelain
            echo "##[error] found changed files after build. please 'npm run pre-checkin'"
            exit 1
          fi
